sudo: required
dist: trusty
language: node_js
node_js:
  # - "4.1"
  # - "0.12"
  # - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"

before_install:
  # Repair npm issues for Travis CI
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

  # Add `dbus` dependency
  - sudo apt-get update
  - sudo apt-get install -y dbus libdbus-1-dev

  # Debug
  # TODO: Remove me
  - env | grep DBU
  - ls /run/dbus || true
  - dbus-launch

notifications:
  email: false
