sudo: required
dist: trusty
language: node_js
node_js:
  # DEV: We currently don't test `node@0.10` due to `nan` issues for `dbus`
  - "5.3"
  - "4.2"
  - "0.12"

before_install:
  # Repair npm issues for Travis CI
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

  # Add `dbus` dependency
  - sudo apt-get update
  - sudo apt-get install -y dbus libdbus-1-dev

  # Start up a dbus instance
  # http://linux.die.net/man/1/dbus-launch
  - eval "$(dbus-launch --sh-syntax)"

notifications:
  email: false
